### ISSUE TITLE
Create Typography Component

### ISSUE THREAD

**Issue by anniehu4** [chanzuckerberg/lp-design-system#205]
# Problem
Currently, we allow a lot of flexibility in styling text elements, which means there are a lot of non-standard sizes, line heights, etc. being used. See [CSS stats](https://cssstats.com/stats/?url=https%3A%2F%2Fcdn.summitlearning.org%2Fassets%2Fclaro_application-88346d781bb0cc90c820223d04b4174266a21d5de4fc8d267746eccdf5ff19b8.css): there are 74 unique font sizes (a mix of px, pt, em, and rem) and 25 unique font families.

# Solution
We will create a Typography component (similar to [Along's Typography](https://github.com/chanzuckerberg/connections/blob/main/client/src/ui/Typography/Typography.tsx)) to consolidate usages of text in the platform.

We will allow props:
- `as`: actual HTML element to render (enum)
- `size`: visual appearance of element (enum)
- `children`: content in text element
- `color`: custom color of text (enum to start)
- ~`className`: a custom CSS class to help with the transition -- may want to remove after~

Naming will follow the [Figma type ramp](https://www.figma.com/file/sKEhNrLEdexPeVVn58dkWx/SDL-(Summit-Design-Language)-Explorations?node-id=980%3A122).

Part of the migration will involve consolidating usages of the LP `Heading` component into this component.

# Benefits
- Enforces greater consistency in how text is used (e.g. all `body` text should have the same root style)
- Allows for incremental migration

# Challenges and Mitigations
We'll need to delegate parts of this migration to scrum teams. Some existing styles might be very high specificity (difficult to override).

## Theming for existing styles & new styles
- Need to be able to migrate LP incrementally, then "flip the switch" at once
- The DS typography styles we have will change again once we go through a rebrand
- Forward work should support new styles

## Coordinating with migration of sizes in CSS
- Base size in traject is `13px` while base size of design system is `16px`
- px -> rem migration
- removing magic numbers

**Comment by dcwither** [comment]
A few additional notes:
- I think removing the className by default would be a good start.
- Color can be an enum of `info, brand, warning, alert, success, black, white`

Additional Challenges:
- Existing styles that are very high specificity
- Theming for both existing styles and new styles
